import 'package:demo_dprofiles/src/utils/https/dio/http_util.dart';
import 'package:demo_dprofiles/src/utils/https/my_response/base_response.dart';
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';

import 'auto_generate_datasource.dart';

@Injectable(as: AutoGenerateDataSource)
class AutoGenerateDataSourceImpl implements AutoGenerateDataSource {
  @override
  Future<BaseResponse> getAutoGenerateHistory() async {
    try {
      final response = await MyHttp.rl().getAutoGenerateHistory();

      return response;
    } on DioException {
      rethrow;
    }
  }
}
