import 'package:demo_dprofiles/src/features/AI/ai_features/data/models/write_cover_letter_model.dart';
import 'package:demo_dprofiles/src/features/AI/ai_features/data/models/write_interview_question_model.dart';
import 'package:demo_dprofiles/src/features/AI/ai_features/data/models/write_profile_introduction_model.dart';
import 'package:demo_dprofiles/src/features/AI/ai_features/data/models/write_skill_knowledge_model.dart';
import 'package:demo_dprofiles/src/utils/https/my_response/base_response.dart';

abstract class AutoGenerateDataSource {
  Future<BaseResponse> getAutoGenerateHistory();

  Future<BaseResponse> generateProfileIntroduction(
      WriteProfileIntroductionModel model);

  Future<BaseResponse> generateInterviewQuestion(
      WriteInterviewQuestionModel model);

  Future<BaseResponse> generateSkillKnowledge(WriteSkillKnowledgeModel model);

  Future<BaseResponse> generateCoverLetter(WriteCoverLetterModel model);
}
