name: demo_dprofiles
description: "Text to speech application"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # animation
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.0

  # wallet
  web3modal_flutter: ^3.1.2

  # support
  uuid: ^4.3.3

  # route
  auto_route: ^7.9.0

  # state management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1

  # dependency injection
  get_it: ^7.6.7
  injectable:

  # cache
  shared_preferences: ^2.2.2
  isar: any
  isar_flutter_libs: *isar_version

  # assets
  flutter_gen: ^5.4.0

  # UI
  google_fonts: 6.1.0
  persistent_bottom_nav_bar: ^5.0.2
  ficonsax: ^0.0.3
  tuple: ^2.0.2
  flex_color_scheme: ^7.3.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  bubble_tab_indicator: ^0.1.6
  pinput: ^4.0.0
  flutter_tts: ^4.0.2
  rounded_background_text: ^0.5.0
  simple_ripple_animation: ^0.0.9

  # https
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.4.1
  path: any
  logger: any
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  retrofit_generator: ">=7.0.0 <8.0.0"
  build_runner: ^2.4.8
  auto_route_generator:
  json_serializable: ^6.7.1
  isar_generator: *isar_version
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.7
  flutter_gen_runner:
  injectable_generator:

flutter_gen:
  output: lib/src/theme

  integrations:
    flutter_svg: true
    flutter_png: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/profile/
    - assets/images/my_wallet/
    - assets/images/ai_features/
    - assets/animations/
    - assets/icons/
    - assets/icons/logos/
